const SectionsData = [
  {
    id: 1,
    course: "HTML",
    topic: "HTML Basics For Beginners",
    url: "https://www.youtube.com/embed/MDLn5-zSQQI",
  },
  {
    id: 2,
    course: "HTML",
    topic: "HTML Semantic Tags in HTML",
    url: "https://www.youtube.com/embed/fhoDRB53DwY",
  },
  {
    id: 3,
    course: "HTML",
    topic: "HTML Hyperlinks",
    url: "https://www.youtube.com/embed/gOioxltfh48",
  },
  {
    id: 4,
    course: "HTML",
    topic: "Image tag in HTML",
    url: "https://www.youtube.com/embed/Hh_se2Zqsdk",
  },
  {
    id: 5,
    course: "HTML",
    topic: "HTML Lists",
    url: "https://www.youtube.com/embed/-kXZvKxs9oA",
  },
  {
    id: 6,
    course: "HTML",
    topic: "HTML Audio tag",
    url: "https://www.youtube.com/embed/uof_zYxtnp0",
  },
  {
    id: 7,
    course: "HTML",
    topic: "HTML Video tag",
    url: "https://www.youtube.com/embed/BAx2GaMW2qA",
  },
  {
    id: 8,
    course: "CSS",
    topic: "Introduction to CSS",
    url: "https://www.youtube.com/embed/uOltiFI00rU",
  },
  {
    id: 9,
    course: "CSS",
    topic: "Types of CSS",
    url: "https://www.youtube.com/embed/ArUL-He_AN0",
  },
  {
    id: 10,
    course: "CSS",
    topic: "Selectors in CSS",
    url: "https://www.youtube.com/embed/Z07d9Vu7GKM",
  },
  {
    id: 11,
    course: "CSS",
    topic: "CSS Background Properties",
    url: "https://www.youtube.com/embed/0A1H6kkKp4E",
  },
  {
    id: 12,
    course: "CSS",
    topic: "CSS Box & Text Shadow",
    url: "https://www.youtube.com/embed/ASNldCkFBcM",
  },
  {
    id: 13,
    course: "CSS",
    topic: "CSS Flex-Box",
    url: "https://www.youtube.com/embed/GteJWhCikCk",
  },
  {
    id: 14,
    course: "CSS",
    topic: "Media-queries",
    url: "https://www.youtube.com/embed/QfYJevoR3OA",
  },
  {
    id: 15,
    course: "JavaScript",
    topic: "Introduction to JS",
    url: "https://www.youtube.com/embed/B7wHpNUUT4Y",
  },
  {
    id: 16,
    course: "JavaScript",
    topic: "Closures",
    url: "https://www.youtube.com/embed/qikxEIxsXco",
  },
  {
    id: 17,
    course: "JavaScript",
    topic: "Filter, Map & Reduce",
    url: "https://www.youtube.com/embed/9MfwYoWKKVE",
  },
  {
    id: 18,
    course: "JavaScript",
    topic: "CallBacks",
    url: "https://www.youtube.com/embed/btj35dh3_U8",
  },
  {
    id: 19,
    course: "JavaScript",
    topic: "Promises",
    url: "https://www.youtube.com/embed/NJwRQgsu1Q8",
  },
  {
    id: 20,
    course: "JavaScript",
    topic: "Async & Await",
    url: "https://www.youtube.com/embed/6nv3qy3oNkc",
  },
  {
    id: 21,
    course: "JavaScript",
    topic: "Spread & Rest Operator",
    url: "https://www.youtube.com/embed/DoIGxx7P-ps",
  },
  {
    id: 22,
    course: "React",
    topic: "Introduction to React",
    url: "https://www.youtube.com/embed/Y6aYx_KKM7A",
  },
  {
    id: 23,
    course: "React",
    topic: "JSX in React",
    url: "https://www.youtube.com/embed/cxV9d6u0vfU",
  },
  {
    id: 24,
    course: "React",
    topic: "Components in React",
    url: "https://www.youtube.com/embed/YcXVT2udeu8",
  },
  {
    id: 25,
    course: "React",
    topic: "Props in React",
    url: "https://www.youtube.com/embed/HRhJVGjIraE",
  },
  {
    id: 26,
    course: "React",
    topic: "Handling Events",
    url: "https://www.youtube.com/embed/smRtYZHv8Bk",
  },
  {
    id: 27,
    course: "React",
    topic: "Routing in React",
    url: "https://www.youtube.com/embed/1N_Vh0bRK3c",
  },
  {
    id: 28,
    course: "React",
    topic: "Hooks in React",
    url: "https://www.youtube.com/embed/SS1I7m-G2kk",
  },
  {
    id: 29,
    course: "Git",
    topic: "Git vs GitHub",
    url: "https://www.youtube.com/embed/xJXgvr8bPes",
  },
  {
    id: 30,
    course: "Git",
    topic: "Git Stage & Commit",
    url: "https://www.youtube.com/embed/yimJop_5lV4",
  },
  {
    id: 31,
    course: "Git",
    topic: "Git Branching",
    url: "https://www.youtube.com/embed/vwik-o0wD5A",
  },
  {
    id: 32,
    course: "Git",
    topic: "Git Stash",
    url: "https://www.youtube.com/embed/lH3ZkwbVp5E",
  },
  {
    id: 33,
    course: "Git",
    topic: "Git Push Command",
    url: "https://www.youtube.com/embed/xJXgvr8bPes",
  },
  {
    id: 34,
    course: "Git",
    topic: "Git Bash",
    url: "https://www.youtube.com/embed/iGutIN5t9Mo",
  },
  {
    id: 35,
    course: "Git",
    topic: "Top 10 Git Commands",
    url: "https://www.youtube.com/embed/PSJ63LULKHA",
  },
];

export default SectionsData;
